# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import inference_service_pb2 as inference__service__pb2


class InferenceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Infer = channel.unary_unary(
                '/inference_service.Inference/Infer',
                request_serializer=inference__service__pb2.InferenceRequest.SerializeToString,
                response_deserializer=inference__service__pb2.InferenceResponse.FromString,
                )
        self.Infer1 = channel.unary_unary(
                '/inference_service.Inference/Infer1',
                request_serializer=inference__service__pb2.Message1.SerializeToString,
                response_deserializer=inference__service__pb2.InferenceResponse.FromString,
                )
        self.Infer2 = channel.unary_unary(
                '/inference_service.Inference/Infer2',
                request_serializer=inference__service__pb2.Message2.SerializeToString,
                response_deserializer=inference__service__pb2.InferenceResponse.FromString,
                )
        self.Infer3 = channel.unary_unary(
                '/inference_service.Inference/Infer3',
                request_serializer=inference__service__pb2.Message3.SerializeToString,
                response_deserializer=inference__service__pb2.Endpoints.FromString,
                )
        self.BandwidthMeasurement = channel.unary_unary(
                '/inference_service.Inference/BandwidthMeasurement',
                request_serializer=inference__service__pb2.BandwidthMeasurementMessage.SerializeToString,
                response_deserializer=inference__service__pb2.BandwidthMeasurementMessage.FromString,
                )


class InferenceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Infer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Infer1(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Infer2(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Infer3(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BandwidthMeasurement(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_InferenceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Infer': grpc.unary_unary_rpc_method_handler(
                    servicer.Infer,
                    request_deserializer=inference__service__pb2.InferenceRequest.FromString,
                    response_serializer=inference__service__pb2.InferenceResponse.SerializeToString,
            ),
            'Infer1': grpc.unary_unary_rpc_method_handler(
                    servicer.Infer1,
                    request_deserializer=inference__service__pb2.Message1.FromString,
                    response_serializer=inference__service__pb2.InferenceResponse.SerializeToString,
            ),
            'Infer2': grpc.unary_unary_rpc_method_handler(
                    servicer.Infer2,
                    request_deserializer=inference__service__pb2.Message2.FromString,
                    response_serializer=inference__service__pb2.InferenceResponse.SerializeToString,
            ),
            'Infer3': grpc.unary_unary_rpc_method_handler(
                    servicer.Infer3,
                    request_deserializer=inference__service__pb2.Message3.FromString,
                    response_serializer=inference__service__pb2.Endpoints.SerializeToString,
            ),
            'BandwidthMeasurement': grpc.unary_unary_rpc_method_handler(
                    servicer.BandwidthMeasurement,
                    request_deserializer=inference__service__pb2.BandwidthMeasurementMessage.FromString,
                    response_serializer=inference__service__pb2.BandwidthMeasurementMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'inference_service.Inference', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Inference(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Infer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/inference_service.Inference/Infer',
            inference__service__pb2.InferenceRequest.SerializeToString,
            inference__service__pb2.InferenceResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Infer1(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/inference_service.Inference/Infer1',
            inference__service__pb2.Message1.SerializeToString,
            inference__service__pb2.InferenceResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Infer2(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/inference_service.Inference/Infer2',
            inference__service__pb2.Message2.SerializeToString,
            inference__service__pb2.InferenceResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Infer3(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/inference_service.Inference/Infer3',
            inference__service__pb2.Message3.SerializeToString,
            inference__service__pb2.Endpoints.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def BandwidthMeasurement(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/inference_service.Inference/BandwidthMeasurement',
            inference__service__pb2.BandwidthMeasurementMessage.SerializeToString,
            inference__service__pb2.BandwidthMeasurementMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
